 
all: clean
	#g++ 2.cpp -o 2
	#g++ 3.cpp -o 3 -g
	g++ 4.cpp -o 4
	#g++ 6.cpp -o 6
	#g++ 7.cpp -o 7
	#g++ 8.cpp -o 8 -g
	#g++ 9.cpp 9.hpp -o 9
	g++ 10.cpp -o 10
	#g++ 11.cpp -o 11
	#g++ 12.cpp 12.hpp -o 12
	#g++ 13.cpp -o 13
	#g++ 14.cpp 14.hpp -o 14
	#g++ 15.cpp -o 15
	#g++ 16.cpp -o 16
	#g++ 17.cpp 17.hpp -o 17
	#g++ 18.cpp -o 18
	#g++ 19.cpp -o 19
	#g++ 20.cpp -o 20 -g

clean:
	rm 2 -f
	rm 3 -f
	rm 4 -f
	rm 6 -f
	rm 7 -f
	rm 8 -f
	rm 9 -f
	rm 10 -f
	rm 11 -f
	rm 12 -f
	rm 13 -f
	rm 14 -f
	rm 15 -f
	rm 16 -f
	rm 17 -f
	rm 18 -f
	rm 19 -f
	rm 20 -f